In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3,30],[4,5,6,31],[7,8,9,32]],
    [[11,12,13,33],[14,15,16,34],[17,18,19,35]],
    [[21,22,23,36],[24,25,26,37],[27,28,29,38]],
])

In [3]:
escalar_t = escalar.T

AttributeError: 'float' object has no attribute 'T'

In [4]:
vector_t = vector.T
print(vector_t)

[3 4 5 6]


In [5]:
matriz_t = matriz.T

In [6]:
print(matriz_t)

[[1 3 5]
 [2 4 6]]


In [7]:
print(matriz.shape)

(3, 2)


In [8]:
print(matriz_t.shape)

(2, 3)


In [9]:
tensor_t = tensor.T
print(tensor_t)

[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]

 [[30 33 36]
  [31 34 37]
  [32 35 38]]]


In [10]:
print(tensor)

[[[ 1  2  3 30]
  [ 4  5  6 31]
  [ 7  8  9 32]]

 [[11 12 13 33]
  [14 15 16 34]
  [17 18 19 35]]

 [[21 22 23 36]
  [24 25 26 37]
  [27 28 29 38]]]


In [11]:
matriz_t_t = matriz_t.T
print(matriz_t_t)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
print(matriz)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
A = matriz
B = matriz_t

In [14]:
C = A+B

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [15]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[6,5],[4,3],[2,1]])
C = A+B
print(A)
print(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[6 5]
 [4 3]
 [2 1]]
[[7 7]
 [7 7]
 [7 7]]


In [16]:
D = matriz + escalar
print(D)

[[ 6.679  7.679]
 [ 8.679  9.679]
 [10.679 11.679]]
