In [1]:
import numpy as np

In [2]:
identidad = np.eye(4)

In [3]:
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
vector = np.array([[2],[3],[5],[7]])

In [5]:
print(identidad.dot(vector))

[[2.]
 [3.]
 [5.]
 [7.]]


In [6]:
print(vector)

[[2]
 [3]
 [5]
 [7]]


In [7]:
A = np.array([[1,0,1],[0,1,1],[-1,1,1]])

In [8]:
print(A)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]


In [9]:
inversa_A = np.linalg.inv(A)

In [10]:
print(inversa_A)

[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


In [11]:
print(A.dot(inversa_A))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
singular = np.array([[1,1],[1,1]])

In [13]:
print(singular)

[[1 1]
 [1 1]]


In [14]:
print(np.linalg.inv(singular))

LinAlgError: Singular matrix